# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-23 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner_engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkscan',
            name='address',
        ),
        migrations.RemoveField(
            model_name='linkscan',
            name='custom_code',
        ),
        migrations.AlterField(
            model_name='linkscan',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='linkscan',
            name='h1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='linkscan',
            name='title',
            field=models.CharField(default='', max_length=400),
        ),
    ]
