# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-23 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner_engine', '0002_auto_20161223_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkscan',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='linkscan',
            name='h1',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='linkscan',
            name='title',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
