# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-24 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner_engine', '0003_auto_20161223_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkscan',
            name='updated',
        ),
    ]
