# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-25 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner_engine', '0004_remove_linkscan_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkscan',
            name='h1',
            field=models.CharField(blank=True, default='h1', max_length=200),
        ),
    ]
