# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-01 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner_engine', '0006_auto_20161225_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkscan',
            name='contains_custom_code',
            field=models.BooleanField(default=True),
        ),
    ]
