# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-22 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_and_links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='link',
            name='address',
            field=models.CharField(default='/', max_length=300),
        ),
        migrations.AlterField(
            model_name='link',
            name='custom_code',
            field=models.TextField(blank=True, default='', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='h1',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
