# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-26 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_and_links', '0002_auto_20161222_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='address',
            field=models.URLField(default='/', max_length=300),
        ),
    ]
