# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-26 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_and_links', '0003_auto_20161226_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.URLField(max_length=250),
        ),
        migrations.AlterField(
            model_name='link',
            name='address',
            field=models.CharField(default='/', max_length=300),
        ),
    ]
